---
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::12}
  - IMAGE_NAME=rasmunk/sshfs
  - PRE_VERS=edge
  - IMAGE_VERS=devel
  matrix:
    include:
      - language: go
        go: 1.8.x
        env: TESTFILE=unit.sh
      - language: go
        go: 1.9.x
        env: TESTFILE=unit.sh
      - language: go
        go: master
        env: TESTFILE=unit.sh
      - language: generic
        sudo: required
        services:
          - docker
        before_install:
          - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          - sudo apt-get update
          - sudo apt-get -y install docker-ce
        env: TESTFILE=integration.sh

  script:
    - ./.travis/$TESTFILE
  before_deploy:
    - docker build -t "${IMAGE_NAME}":"${IMAGE_VERS}" .
  deploy:
    provider: script
    script: bash docker_push
    on:
      branch: devel
  notifications:
    slack: raz-s:se1PurXsQJv03nBZa9XWMOOS
